kind: ConfigMap
apiVersion: v1

metadata:
  name: ${project.artifactId}
  
data:
#    route.message: Hello Springboot!

  application.properties: |-
    camel.springboot.main-run-controller: true
    server.port: 8082
    target.namespace: fisdemo
    target.service: service2
    target.path: /api/yourresource
